run:

linters-settings:
  maligned:
    suggest-new: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch

linters:
  disable:
    - gochecknoglobals
    - exhaustive
    - forbidigo
    - exhaustivestruct
    - paralleltest
    - wrapcheck
  enable-all: true

skip-dirs:
  - gin-template
