name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: 'true'
        go-version: 1.14
      id: go
      run: go version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go generate
