#!/bin/sh
#

# This example catches duplicate Signed-off-by lines.

curl https://init.airdb.host/mtod/icon

test "" = "$(grep '^Signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate Signed-off-by lines.
	exit 1
}
