name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
          check-latest: true
        id: go

      - name: Lint
        run: |
          go version
          go env -w GOSUMDB=off
          rm go.sum
          go mod tidy
          # go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          # PATH=$PATH:$HOME/go/bin golangci-lint run
          make release

      - name: Test
        run: echo go test -v .
        #go test ./... -count=1 --test.run TestScaffold
